#!/usr/bin/env bash
# Displays information about subdomains.

# colors
blue='\e[1;34m'
brown='\e[0;33m'
reset='\033[0m'

# variables & parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

dig_cmd () {
    # func variables
    sub="$2"
    INFO="$(dig "$sub.$domain" +short)"
    if [ -z "$INFO" ]; then
        echo "The subdomain $sub does not exist."
        return
    fi
    IP=$(echo "$INFO" | awk 'NR==1')
    RECORD="A"

    echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
}

if [ -z "$domain" ]; then
    echo "No domain provided."
    exit 1
fi

if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$domain" "$sub"
fi