#!/usr/bin/env bash
# Displays information about subdomains.

# variables & parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

# mapping from IP addresses to server names
declare -A ip_to_name=( ["52.72.21.138"]="web-02" )

dig_cmd () {
    # func variables
    sub="$2"
    INFO="$(dig "$sub.$domain" +short)"
    if [ -z "$INFO" ]; then
        echo "The subdomain $sub does not exist."
        return
    fi
    IP=$(echo "$INFO" | awk 'NR==1')
    RECORD="A"
    NAME=${ip_to_name["$IP"]}

    echo "The subdomain $sub is a $RECORD record and points to $NAME"
}

if [ -z "$domain" ]; then
    echo "No domain provided."
    exit 1
fi

if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$domain" "$sub"
fi