#!/user/bin/env bash
# configur a ufw firewall to block all incoming trafic
#   except for tcp ports 22, 80, and 443.

sudo apt install ufa
sudo ufw default deny incoming
sudo ufw default allow  outgoing 
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
